name: lol-analysis-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.23.5
  - seaborn=0.12.2
  - matplotlib=3.7.1
  - ipython=8.12.2
  - ipykernel=6.23.1
  - pip:
    - tabulate
    - jupyter
    - scikit-learn
